# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3ac356b35c20aa381c6b058c3b5bdb3494e8ef28fb888f79e1260fd7d8d7cbab39e3c85efe469a0175652dbfb8de84b4648ec95872fbc834c05cf3af46afd0c5

test:
  secret_key_base: 811d397eb5da9b5d5491f91e9f366e8dc38a2e6adeb49f3eb2130f9df852eea45df5aa26d7b8113ae0b89e37c22206abe6fddeace65111eb8f9611e654d5a79a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
